export default [
    {
        title: "插件编号",
        key: "plId",
        minWidth: 100,
        showPos: 'draw',
    },
    {
        title: "插件类型",
        key: "typeId",
        minWidth: 100,
        showPos: 'table',
        slot: "v-avatar",
    },
    {
        title: "插件版块",
        key: "blockId",
        minWidth: 100,
        showPos: 'table',
        slot: "v-btn",
    },
    {
        title: "首图",
        key: "plImg",
        minWidth: 100,
        showPos: 'table',
        slot: "v-date",
    },
    {
        title: "标题",
        key: "plTitle",
        minWidth: 100,
        showPos: 'table',
        slot: "v-drawer",
    },
    {
        title: "内容详情",
        key: "plDetail",
        minWidth: 100,
        showPos: 'table',
        slot: "v-img",
    },
    {
        title: "排序",
        key: "plOrder",
        minWidth: 100,
        showPos: 'table',
        slot: "v-input",
    },
    {
        title: "文件大小",
        key: "plFileSize",
        minWidth: 100,
        showPos: 'table',
        slot: "v-inputNumber",
    },
    {
        title: "创建时间",
        key: "createDate",
        minWidth: 100,
        showPos: 'table',
        slot: "v-link",
    },
    {
        title: "更新时间",
        key: "updateDate",
        minWidth: 100,
        showPos: 'table',
        slot: "v-radio",
    },
    {
        title: "备注",
        key: "info",
        minWidth: 100,
        showPos: 'table',
        slot: "v-rate",
    },
]