export default [
    {
        title: "插件编号",
        key: "plId",
        minWidth: 100,
        showPos: 'table',
        tableSlot: "v-html",
    },
    {
        title: "插件类型",
        key: "typeId",
        minWidth: 100,
        showPos: 'table;drawer;search',
        tableDisabled: true,
        tableSlot: "v-selectSpan",
        slot: "v-select",
        optionKey: 'typeId',
        optionTitle: 'typeName',
        optionsApi: '/protype/pager',
        optionsParams: {
            start: 0,
            length: 10000,
            type: '1'
        },
    },
    {
        title: '评分',
        key: 'plVal',
        showPos: 'table;drawer',
        tableDisabled: true,
        maxRate: 100,
        minRate: 0,
        tableSlot: "v-rate",
        minWidth: 150
    },
    {
        title: "插件版块",
        key: "blockId",
        minWidth: 100,
        showPos: 'table;drawer;search',
        optionKey: 'typeId',
        tableDisabled: true,
        optionTitle: 'typeName',
        optionsApi: '/protype/pager',
        optionsParams: {
            start: 0,
            length: 10000,
            type: '2'
        },
        tableSlot: "v-selectSpan",
        slot: "v-select",

    },
    {
        title: "首图",
        key: "plImg",
        minWidth: 100,
        showPos: 'table',
        tableSlot: "v-img",
    },
    {
        title: "标题",
        key: "plTitle",
        minWidth: 100,
        showPos: 'table',
        tableSlot: "v-html",
    },
    {
        title: "内容详情",
        btnTitle: '查看详情',
        key: "plDetail",
        minWidth: 100,
        showPos: 'table',
        slot: "v-img",
        tableSlot: "v-btn",
    },
    {
        title: "排序",
        key: "plOrder",
        minWidth: 100,
        showPos: 'table',
        slot: "v-input",
        tableSlot: "v-html",
    },
    {
        title: "文件大小",
        key: "plFileSize",
        minWidth: 100,
        showPos: 'table',
        tableSlot: "v-filesize",
    },
    {
        title: "创建时间",
        key: "createDate",
        minWidth: 100,
        showPos: 'table',
        slot: "v-dateSpan",
        tableSlot: "v-dateSpan",

    },
    {
        title: "更新时间",
        key: "updateDate",
        minWidth: 100,
        showPos: 'table',
        tableSlot: "v-dateSpan",
    },
    {
        title: "备注",
        key: "info",
        minWidth: 50,
        showPos: 'table',
        slot: "v-html",
    },
    {
        title: "新增",
        btnTitle: '新增',
        key: "create",
        minWidth: 50,
        showPos: 'search',
        cla: 'pos-right',
        slot: "v-btn",
    },
]