export default [
    {
        title: '首页',
        cla: '',
        icon: 'HomeOutlined',
        role: '',
        disabled: '',
        jump: '/home',
        idx: 'menu_1',
        category: [
            {
                title: '分组一',
                children: [
                    {
                        title: '选项1',
                        jump: '',
                        idx: 'menu_1-1',
                        children: [
                            {
                                title: '选项32',
                                jump: '',
                                idx: 'menu_11',
                            }, {
                                title: '选项31',
                                jump: '',
                                idx: 'menu_22',
                            },
                        ],
                    },
                    {
                        title: '选项2',
                        jump: '',
                        idx: 'menu_1-2',
                    },
                ],
            },
            {
                title: '分组二',
                children: [
                    {
                        title: '选项3',
                        jump: '',
                        idx: 'menu_2',
                    },
                    {
                        title: '选项4',
                        jump: '',
                        idx: 'menu_3',
                    },
                ],
            },
        ],
    },
    {
        title: '文档',
        cla: '',
        role: '',
        icon: 'FileExcelOutlined',
        disabled: '',
        jump: '/document',
        children: [
            {
                title: '选项3',
                jump: '',
                idx: 'menu_4'
            },
            {
                title: '选项4',
                jump: '',
                idx: 'menu_5',
            },
        ],
    },
    {
        title: '引导页',
        cla: '',
        role: '',
        icon: 'SendOutlined',
        disabled: '',
        jump: '/guid',
        idx: 'menu_6',
    },
    {
        title: '图标',
        cla: '',
        role: '',
        icon: 'LockOutlined',
        disabled: '',
        jump: '/icon',
        idx: 'menu_7',
    },
    {
        title: '组件',
        cla: '',
        role: '',
        icon: 'LockOutlined',
        disabled: '',
        jump: '/role',
        idx: 'menu_7',
    },
    {
        title: '图表',
        cla: '',
        role: '',
        icon: 'LockOutlined',
        disabled: '',
        jump: '/role',
        idx: 'menu_7',
    },
    {
        title: '路由嵌套',
        cla: '',
        role: '',
        icon: 'LockOutlined',
        disabled: '',
        jump: '/role',
        idx: 'menu_7',
    },
    {
        title: 'Table',
        cla: '',
        role: '',
        icon: 'LockOutlined',
        disabled: '',
        jump: '/role',
        idx: 'menu_7',
    },
    {
        title: '综合实例',
        cla: '',
        role: '',
        icon: 'LockOutlined',
        disabled: '',
        jump: '/role',
        idx: 'menu_7',
    },
    {
        title: 'Tab',
        cla: '',
        role: '',
        icon: 'LockOutlined',
        disabled: '',
        jump: '/role',
        idx: 'menu_7',
    },
    {
        title: '错误页面',
        cla: '',
        role: '',
        icon: 'LockOutlined',
        disabled: '',
        jump: '/role',
        idx: 'menu_7',
    },
    {
        title: '错误日志',
        cla: '',
        role: '',
        icon: 'LockOutlined',
        disabled: '',
        jump: '/role',
        idx: 'menu_7',
    },
    {
        title: 'Excel',
        cla: '',
        role: '',
        icon: 'LockOutlined',
        disabled: '',
        jump: '/role',
        idx: 'menu_7',
    },
    {
        title: 'Zip',
        cla: '',
        role: '',
        icon: 'LockOutlined',
        disabled: '',
        jump: '/role',
        idx: 'menu_7',
    },
    {
        title: 'PDF',
        cla: '',
        role: '',
        icon: 'LockOutlined',
        disabled: '',
        jump: '/role',
        idx: 'menu_7',
    },
    {
        title: '换肤',
        cla: '',
        role: '',
        icon: 'LockOutlined',
        disabled: '',
        jump: '/role',
        idx: 'menu_7',
    },
    {
        title: 'Clipboard',
        cla: '',
        role: '',
        icon: 'CopyOutlined',
        disabled: '',
        jump: '/role',
        idx: 'menu_7',
    },
    {
        title: '国际化',
        cla: '',
        role: '',
        icon: 'DribbbleOutlined',
        disabled: '',
        jump: '/role',
        idx: 'menu_7',
    },
    {
        title: '外链',
        cla: '',
        role: '',
        icon: 'LinkOutlined',
        disabled: '',
        jump: '/role',
        idx: 'menu_7',
    },
];
