export default [
    {
        title: '首页',
        cla: '',
        icon: 'HomeOutlined',
        role: '',
        disabled: '',
        jump: '/dashboard',
        idx: 'dashboard',
    },
    {
        title: '文档',
        cla: '',
        role: '',
        icon: 'FileExcelOutlined',
        disabled: '',
        jump: '/home',
        idx: 'home',
        children: [
            {
                title: '选项3',
                jump: '/home',
                idx: 'home'
            },
            {
                title: '选项4',
                jump: '/home',
                idx: 'home',
            },
        ],
    },
    {
        title: '引导页',
        cla: '',
        role: '',
        icon: 'SendOutlined',
        disabled: '',
        jump: '/guide',
        idx: 'guide',
    },
    {
        title: '图标',
        cla: '',
        role: '',
        icon: 'LockOutlined',
        disabled: '',
        jump: '/icons',
        idx: 'icons',
    },
    {
        title: '组件',
        cla: '',
        role: '',
        icon: 'LockOutlined',
        disabled: '',
        jump: '/components',
        idx: 'components',
    },
    {
        title: '图表',
        cla: '',
        role: '',
        icon: 'BarChartOutlined',
        disabled: '',
        jump: '/chart',
        idx: 'chart',
    },
    {
        title: '路由嵌套',
        cla: '',
        role: '',
        icon: 'LockOutlined',
        disabled: '',
        category: [
            {
                title: '分组1',
                children: [
                    {
                        title: '分组1-1',
                        jump: '/home',
                        idx: 'home-1'
                    },
                    {
                        title: '分组1-2',
                        children: [
                            {
                                title: '选项1-2-1',
                                jump: '/home',
                                idx: 'home',
                            }, {
                                title: '选项1-2-2',
                                jump: '/home',
                                idx: 'home',
                            },
                        ],
                    },
                ],
            },
            {
                title: '分组2',
                children: [{
                    title: '分组2-1'
                }, {
                    title: '分组2-2'
                }]
            },
        ],
    },
    {
        title: 'Table',
        cla: '',
        role: '',
        icon: 'TableOutlined',
        disabled: '',
        jump: '/table',
        idx: 'table',
    },
    {
        title: '综合实例',
        cla: '',
        role: '',
        icon: 'LockOutlined',
        disabled: '',
        jump: '/example',
        idx: 'example',
    },
    {
        title: 'Tab',
        cla: '',
        role: '',
        icon: 'LockOutlined',
        disabled: '',
        jump: '/tab',
        idx: 'tab',
    },
    {
        title: '错误页面',
        cla: '',
        role: '',
        icon: 'LockOutlined',
        disabled: '',
        jump: '/404',
        idx: '404',
    },
    {
        title: '错误日志',
        cla: '',
        role: '',
        icon: 'LockOutlined',
        disabled: '',
        jump: '/error',
        idx: 'error',
    },
    {
        title: 'Excel',
        cla: '',
        role: '',
        icon: 'LockOutlined',
        disabled: '',
        jump: '/excel',
        idx: 'excel',
    },
    {
        title: 'Zip',
        cla: '',
        role: '',
        icon: 'LockOutlined',
        disabled: '',
        jump: '/zip',
        idx: 'zip',
    },
    {
        title: 'PDF',
        cla: '',
        role: '',
        icon: 'LockOutlined',
        disabled: '',
        jump: '/pdf',
        idx: 'pdf',
    },
    {
        title: '换肤',
        cla: '',
        role: '',
        icon: 'LockOutlined',
        disabled: '',
        jump: '/skin',
        idx: 'skin',
    },
    {
        title: 'Clipboard',
        cla: '',
        role: '',
        icon: 'CopyOutlined',
        disabled: '',
        jump: '/copy',
        idx: 'copy',
    },
    {
        title: '国际化',
        cla: '',
        role: '',
        icon: 'DribbbleOutlined',
        disabled: '',
        jump: '/iin8',
        idx: 'iin8',
    },
    {
        title: '外链',
        cla: '',
        role: '',
        icon: 'LinkOutlined',
        disabled: '',
        jump: '/link',
        idx: 'link',
    },
];
